language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - gem install bundler
  - bundle install
  - ./gradlew assemble
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - bundle exec danger