language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew assemble
  - ./gradlew test
  - bash <(curl -s https://codecov.io/bash)
  - gem install bundler && bundle install && bundle exec danger