language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew assemble
  - gem install bundler
  - bundle install
  - bundle update danger
  - bundle exec danger --verbose
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
