build:
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1
    detekt-hint: 0

detekt-hint:
  UseCompositionInsteadOfInheritance:
    active: true
    yourUniquePackageName: "com.airthings.airthings"
  LackOfCohesionMethods:
    active: true
    threshold: "0.8"
  InterfaceSegregationPrinciple:
    active: true
  OpenClosedPrinciple:
    active: true

